# ========================== H2 ==========================
#spring.application.name=controleFinanceiro
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
##console do H2 habilitado
#spring.h2.console.enabled=true
# ========================== H2 ==========================


# ==========================
# PostgreSQL
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/controle_financeiro
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Hibernate
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true